### ISSUE TITLE
New release 5.0.4 ignores max-line-length in pyproject.toml

### ISSUE THREAD

**Issue by roniemartinez** [csachs/pyproject-flake8#18]
https://github.com/roniemartinez/amortization/runs/8292770323?check_suite_focus=true
https://github.com/roniemartinez/latex2mathml/runs/8292884931?check_suite_focus=true

**Comment by csachs** [comment]
Argh ... I didn't test it with Python 3.7... fix is underway.

**Comment by csachs** [comment]
The patching for the new flake8 5 major release changed. I had merged the updated patching in the night, and to differentiate from pflake8's standpoint between older and newer flake8 versions, pushed a set of new versions to match flake8's versions.

However, I didn't test the new updated patching with older Python versions. I'm sorry, I've now added a quick test for Python 3.6 to 3.10 via Github Actions.

I'd prefer not to push out every 5.0.x version anew, since they should at least work normally with Python 3.8+.

@roniemartinez please find the updated post-release version `5.0.4.post1`, it should work with Python 3.6-3.10 now.
(e.g., if using pip: `pip install pyproject-flake8==5.0.4.post1`).

**Comment by roniemartinez** [comment]
@csachs 

It worked! Thanks for your effort. 🙇
