### ISSUE TITLE
pflake8 6.0.0 overrides some pyproject.toml parameters with default values when jobs>1

### ISSUE THREAD

**Issue by betapl3b** [csachs/pyproject-flake8#24]
Each worker of flake8 ignores `pyproject.toml` in `--jobs` > 1 executions.

Steps to reproduce:

I have to files (`file1.py`, `file2.py`) with same content:
```
print("long line =============================================================================================")
```
It violates 2 rules: W292 (newline in EOF) and E501 (max-line-length)

In my `pyproject.toml` file I have following flake8 configuration:
```
[tool.flake8]
max-line-length = 120
ignore = "W292"
```
Running `pflake8 -vv --jobs=2` on version 5.0.4. works fine. However same command on version 6.0.0 raises E501 with default 79 char parameter.
```
.\file1.py:1:80: E501 line too long (112 > 79 characters)
.\file2.py:1:80: E501 line too long (112 > 79 characters)
```

Full execution logs are attached:
[5_0_4.txt](https://github.com/csachs/pyproject-flake8/files/10217759/5_0_4.txt)
[6_0_0.txt](https://github.com/csachs/pyproject-flake8/files/10217761/6_0_0.txt)

On line 92 of 6_0_0.txt I can see that parameter from toml file is used. But then each worker reads config again but this time not reading toml file configuration.

**Comment by csachs** [comment]
Thanks for bringing up this issue @betapl3b .

The problem seems to be related to the way the processes are launched under Windows compared to e.g. Linux, `multiprocessing` uses the `spawn` method to actually start completely new processes, while instead on unixoid OS the `fork` method is used, where the monkey patches are inherited. With the new processes under Windows, the monkey patches of `pyproject-flake8` are not loaded.

I've adapted a branch ( https://github.com/csachs/pyproject-flake8/pull/25 ) , could you maybe test if it fixes the issue for you?
```
# either 
pip install git+https://github.com/csachs/pyproject-flake8.git@fix-windows-mp
# or 
pip install https://github.com/csachs/pyproject-flake8/archive/refs/heads/fix-windows-mp.zip
```
Thanks!

**Comment by betapl3b** [comment]
Hi @csachs!

My case seems to be working fine with this fix. Will you merge it into new version soon?

Thanks!

**Comment by csachs** [comment]
@betapl3b versions https://pypi.org/project/pyproject-flake8/6.0.0.post1/ and https://pypi.org/project/pyproject-flake8/6.0.0a1.post1/ are out, upgrading like normal should get you the fix, similarly any fresh installs should pick it up.
